//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetApiReact.Data.Models
{
    using System;
    using System.Collections.Generic;
    using SQ.Core.Data;

    public partial class User : BaseEntity
    {
        public User()
        {
            this.UserActivities = new HashSet<UserActivities>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public UserStatus Status { get; set; }
    
        public virtual ICollection<UserActivities> UserActivities { get; set; }
    }
}
